COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
#  SQLALCHEMY_DATABASE_URI: 'sqlite://'
#  SQLALCHEMY_DATABASE_URI: 'sqlite:///device_db.sqlite'
  SQLALCHEMY_DATABASE_URI: 'mysql://su:Aboba1234!@deolanosdblab1.mysql.database.azure.com/test'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://su:Aboba1234!@deolanosdblab1.mysql.database.azure.com/test'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: su
  MYSQL_ROOT_PASSWORD: Aboba1234!
