name: Build and Push to ACR

on:
  push:
    branches: master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Log in to ACR
      run: az acr login --name ${{ secrets.REGISTRY_NAME }}

    - name: Build and tag Docker image
      run: |
        IMAGE=${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest
        docker build -t $IMAGE .
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Push image to ACR
      run: docker push $IMAGE
